Normalize os dados e compute 3 matrizes de dissimilaridade (uma para cada tabela de dados mfeat-fac (VIEW1), mfeat-fou (VIEW2), mfeat-kar (VIEW3)) usando a distancia Euclidiana.
Execute o algoritmo "Partitioning fuzzy K-medoids clustering algorithms with relevance weight for each dissimilarity matrix estimated locally" 100 vezes para obter uma partição fuzzy em 10 grupos e selecione o melhor resultado segundo a função objetivo, considerando os seguintes casos: i) simultaneamente nessas 3 matrizes de dissimilaridade; ii) em cada uma delas individualmente.

In [ ]:
# imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from google.colab import drive
import argparse
import sys,os
from sklearn import preprocessing
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform
import random

In [ ]:

dir_remoto = "/content/drive/My Drive/"
dir_local = os.getcwd() # path para rodar em máquina local ao invés do colab

kar = pd.read_csv(os.path.join(dir_remoto,'data/mfeat-kar'),  delim_whitespace=True, header= None)
fou = pd.read_csv(os.path.join(dir_remoto,'data/mfeat-fou'),  delim_whitespace=True, header= None)
fac = pd.read_csv(os.path.join(dir_remoto,'data/mfeat-fac'),  delim_whitespace=True, header= None)

print("mfeat-kar")
print(kar.shape, kar.head())
print("mfeat-fou")
print(fou.shape, fou.head())
print("mfeat-fac")
print(fac.shape, fac.head())

mfeat-kar
(2000, 64)           0          1          2   ...        61        62        63
0 -10.297008 -11.666789  11.560669  ...  1.814691 -1.351353 -0.473910
1  -5.036009 -12.885333   0.161155  ...  0.485792  0.642451  0.613107
2  -9.639157  -6.655898   0.388687  ...  1.097748  0.827182 -1.767840
3  -6.650375  -7.043851   4.104350  ... -0.913552 -0.771735  0.304992
4 -10.664524 -10.974133   0.194391  ...  0.298318 -0.943213  1.149847

[5 rows x 64 columns]
mfeat-fou
(2000, 76)          0         1         2   ...        73        74        75
0  0.065882  0.197312  0.103826  ...  0.394366  0.049971  0.344871
1  0.049142  0.175971  0.105515  ...  0.445277  0.083978  0.354092
2  0.034172  0.227649  0.108766  ...  0.445029  0.071234  0.261465
3  0.062336  0.217979  0.080243  ...  0.408291  0.063010  0.401376
4  0.061970  0.198358  0.111239  ...  0.434701  0.069218  0.405403

[5 rows x 76 columns]
mfeat-fac
(2000, 216)    0    1    2    3    4    5    6    ...  209  210  211  212  213  

# **Normalizando os Dados**

In [ ]:
def normalization(data):
  x = data.values #returns a numpy array
  min_max_scaler = preprocessing.MinMaxScaler()
  x_scaled = min_max_scaler.fit_transform(x)
  datapd = pd.DataFrame(x_scaled)
  return datapd

kar = normalization(kar)
fou = normalization(fou)
fac = normalization(fac)

print("mfeat-kar")
print(kar.shape, kar.head())
print("mfeat-fou")
print(fou.shape, fou.head())
print("mfeat-fac")
print(fac.shape, fac.head())

mfeat-kar
(2000, 64)          0         1         2   ...        61        62        63
0  0.191173  0.128265  0.889728  ...  0.836661  0.219735  0.433051
1  0.354385  0.089040  0.498033  ...  0.618422  0.565718  0.595312
2  0.211582  0.289563  0.505851  ...  0.718921  0.597774  0.239905
3  0.304303  0.277075  0.633523  ...  0.388613  0.320316  0.549319
4  0.179772  0.150561  0.499175  ...  0.587634  0.290560  0.675432

[5 rows x 64 columns]
mfeat-fou
(2000, 76)          0         1         2   ...        73        74        75
0  0.155955  0.247037  0.148847  ...  0.628352  0.095886  0.588917
1  0.113125  0.219041  0.151407  ...  0.711892  0.162660  0.604874
2  0.074823  0.286835  0.156336  ...  0.711485  0.137636  0.444575
3  0.146884  0.274150  0.113103  ...  0.651201  0.121489  0.686703
4  0.145945  0.248410  0.160085  ...  0.694537  0.133679  0.693673

[5 rows x 76 columns]
mfeat-fac
(2000, 216)         0         1         2    ...       213       214       215
0  0.069196  0.3202

# **Matriz de Dissimilaridade**

In [ ]:

def dissimilaridade(data):
  pairwise = pd.DataFrame(squareform(pdist(data)),columns = data.index,index = data.index)
  return pairwise

# default metric: euclidian distance para a função pdist

matriz_kar = dissimilaridade(kar)
matriz_fou = dissimilaridade(fou)
matriz_fac = dissimilaridade(fac)


print("mfeat-kar")
print(matriz_kar.shape, matriz_kar)
print("mfeat-fou")
print(matriz_fou.shape, matriz_fou)
print("mfeat-fac")
print(matriz_fac.shape, matriz_fac)

mfeat-kar
(2000, 2000)           0         1         2     ...      1997      1998      1999
0     0.000000  1.270193  1.397034  ...  1.605476  1.375733  1.655586
1     1.270193  0.000000  1.470758  ...  1.616383  1.314507  1.666247
2     1.397034  1.470758  0.000000  ...  1.495470  1.353730  1.698088
3     1.330976  1.379091  1.438538  ...  1.469890  1.398961  1.585118
4     1.333689  1.141953  1.638747  ...  1.773640  1.408295  1.821250
...        ...       ...       ...  ...       ...       ...       ...
1995  1.589321  1.776687  1.552311  ...  1.389383  1.157987  1.394733
1996  1.567723  1.378748  1.741908  ...  1.686252  1.467261  1.342234
1997  1.605476  1.616383  1.495470  ...  0.000000  1.246467  1.742059
1998  1.375733  1.314507  1.353730  ...  1.246467  0.000000  1.466838
1999  1.655586  1.666247  1.698088  ...  1.742059  1.466838  0.000000

[2000 rows x 2000 columns]
mfeat-fou
(2000, 2000)           0         1         2     ...      1997      1998      1999
0     0.000000  

In [ ]:
## salvando as matrizes
#matriz_kar.to_csv(os.path.join('data/matriz_kar.csv'), sep = ";")
#matriz_fou.to_csv(os.path.join('data/matriz_fou.csv'), sep = ";")
#matriz_fac.to_csv(os.path.join('data/matriz_fac.csv'), sep = ";")

In [ ]:
# PARÂMETROS INICIAIS

K = 10 # Número de classes
N = 2000 # Número de objetos
t = 0 # tempo inicial
m = 1.6 # valor m 
T = 8  # Número máximo de rodadas
e = 1e-10 # Erro permissível
s = 1 # valor s 
q = 1 # cardinalidade q

In [ ]:
# Criar a matriz de dissimilaridade com P visoões
dj = matriz_kar # Matriz Kar
di = matriz_fou # Matriz Fou
dz = matriz_fac # Matriz Fac
Dj = [[0],[0],[0]] # Cria-se uma matriz nula
Dj[0] = dj # Acrescenta na posição 0, a matriz Kar
Dj[1] = di # Acrescenta na posição 1, a matriz Fou
Dj[2] = dz # Acrescenta na posição 2, a matriz Fac
print(Dj)

[          0         1         2     ...      1997      1998      1999
0     0.000000  1.270193  1.397034  ...  1.605476  1.375733  1.655586
1     1.270193  0.000000  1.470758  ...  1.616383  1.314507  1.666247
2     1.397034  1.470758  0.000000  ...  1.495470  1.353730  1.698088
3     1.330976  1.379091  1.438538  ...  1.469890  1.398961  1.585118
4     1.333689  1.141953  1.638747  ...  1.773640  1.408295  1.821250
...        ...       ...       ...  ...       ...       ...       ...
1995  1.589321  1.776687  1.552311  ...  1.389383  1.157987  1.394733
1996  1.567723  1.378748  1.741908  ...  1.686252  1.467261  1.342234
1997  1.605476  1.616383  1.495470  ...  0.000000  1.246467  1.742059
1998  1.375733  1.314507  1.353730  ...  1.246467  0.000000  1.466838
1999  1.655586  1.666247  1.698088  ...  1.742059  1.466838  0.000000

[2000 rows x 2000 columns],           0         1         2     ...      1997      1998      1999
0     0.000000  1.353952  1.308675  ...  2.243905  1.966262 

In [ ]:
P = len(Dj) # Número de Partições Fuzzy
print(P)

# Matriz V de vetores de pesos de relevância
v = np.arange(K*P)  
v = v.reshape((K, P))
v = np.ones_like(v, dtype=float) # Inicialmente é igual a 1 para todo v_kj
print('v =',v)

# Matriz U (dimensão NxK)
U = np.arange(N*K) 
U = U.reshape((N, K))
U = np.zeros_like(U, dtype=float) # Inicialmente é igual a 0 para todo U_ik
print('U =',U)


3
v = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
U = [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# Função de Adequação "J" (Equações: 06 e 07)
def FMatching(ki, ii): # Equação 07
  vkj1 = 0
  for j in range(0,P):
    dj1 = 0
    for e in G[ki]:
      dj1 += Dj[j][ii][e-1]
    vkj1 += dj1 * v[ki][j]
  return vkj1

def fitnessFunction(): # Equação 06
  J = 0
  for i in range(0, N):
    for j in range(0, K):
      J += ((U[i][j])**m) * FMatching(j, i)
  return J

# Etapa 1: Cálculo dos melhores protótipos (Procedimento 2.3):
# A partição Fuzzy U e o vetor de vetores de pesos de relevância V_k são fixos
def prototype(clt, G_verificação):
  G_out = [] # Para armazenar os prototipos para todos os K cluster
  G_in = []  # Para armazenar os argumentos internos de cada k
  for h in range(0, N):
    G_in.append(argumentos(clt, h))
  L = np.argmin(G_in, axis=0)
  while len(G_out) == 0:
    if (L+1) not in G_verificação:
      G_out.append(L+1)
    else:
      G_in[L] = 10000000000
      L = np.argmin(G_in, axis=0)
  return G_out[0]

def argumentos(ki, hi): # Essa função vai retornar o calculo dos somatórios para o k-ésimo cluster e o h-éssimo argumento.
  L = 0
  somaUVD = 0
  for i in range(0, N):
    somaVD = 0
    for j in range(0, P):
       somaVD += ((v[ki][j])**s) * Dj[j][i][hi] # Não ficou tão claro na função, se ele soma também cada matriz de dissimilaridade Dj para as p visões diferentes
    somaUVD += ((U[i][ki])**m) * somaVD
  L += somaUVD
  return L

#Etapa 2: Cálculo do melhor vetor de pesos de relevância das visões nos grupos (Equação 09)
# Partição Fuzzy U e vetor de representantes G fixos!
def relevanceWeights(ki, ji):
  prodUP = 1
  for h in range(0, P):
    uik2 = 0
    for i in range(0,N):
      DjUp2 = 0
      for e in G[ki]:
        DjUp2 += Dj[h][i][(e)-1]
      uik2 += ((U[i][ki])**m) * DjUp2
    prodUP *= uik2
  DjUDown2 = 0
  for i in range(0,N):
    DjDown2 = 0
    for e in G[ki]:
      DjDown2 += Dj[ji][i][(e)-1]
    DjUDown2 += ((U[i][ki])**m) * DjDown2 
  resultado = (prodUP**(1/P))/(DjUDown2)
  return resultado

# Etapa 3: Definição da Melhor Partição Fuzzy (Equação 11)
# Vetores de representantes G e vetores dos pesos V são fixos!
def fuzzyPartition(ii, ki, s):
  total3 = 0
  soma3 = 0
  for h in range(0,K):
    vikUP3 = 0
    for j in range(0,P):
      djUP3 = 0
      for e in G[ki]:
        djUP3 += Dj[j][ii][(e)-1]
      vikUP3 += (v[ki][j]**s) * djUP3
    vikDown3 = 0
    for j in range(0,P):
      djDown3 = 0
      for e in G[h]:
        djDown3 += Dj[j][ii][(e)-1]
      vikDown3 += (v[h][j]**s) * djDown3
    if vikDown3 == 0:
      soma3 += 0
    else:
      soma3 += (vikUP3/vikDown3)**(1/(m-1))
  if soma3 == 0:
    total3 = 0
  else:
    total3 = (soma3**(-1))
  return total3


In [ ]:
import time
inicio=time.time()

# Algoritmo, união de todas as etapas:

#1) Inicialização
Jt = [10000000] # A lista de soluções J inicia com números com diferença bem alta
t = 0 # tempo inicial
# Matriz de representantes Gk para cada cluster k
G = []
check_list = []
for c in range(0,K):
  G_i = []
  while len(G_i) < q:
    num = random.randint(1,N)
    if num not in check_list:
      G_i.append(num)
      check_list.append(num)
  G.append(G_i)
print('G(t=0)=',G)
print('')
# Para o grau de pertinência Uik inicial.
for i in range(0,N):
  for k in range(0,K):
    U[i][k] = fuzzyPartition(i, k, s)
print("U_ij (t=0)", U) # A matriz com a Partição Fuzzy calculada na Inicialização
print('')
Jt.append(fitnessFunction()) # Etapa Inicial para o J(0)
print("J(t=0)", Jt[-1])
parada = True
while parada == True:
  if ((Jt[-2]-Jt[-1]) > e) and (t < T):
    t += 1
    #2) Etapa 1:
    G_verificação = []  # Uma lista para armazenar todos os protótipos de G e servir para verificar se o elemento eL já está na lista
    for cluster in range(0,K):
      eL = []
      while len(eL) < q:
        eL.append(prototype(cluster, G_verificação))
        if len(eL) == 1:
          G_verificação.append(eL[0])
        elif len(eL) == 2:
          G_verificação.append(eL[1])
      G[cluster] = eL
    print(G)

    #3) Etapa 2:
    for k in range(0, K):
      for j in range(0, P):
        v[k][j] = relevanceWeights(k, j) 
    
    #4) Etapa 3:
    for i in range(0,N):
      for k in range(0,K):
        U[i][k] = fuzzyPartition(i, k, s)

    #5) Critério de parada:
    Jt.append(fitnessFunction())
    print("ERRO", abs(Jt[-1]-Jt[-2]))
    print("t = %.f e J(t) = %.10f" %(t, Jt[-1]))
    print('')
    #print("U = ",U)
    #print("V = ",v)
  else:
    parada = False
    print("FIM do algoritmo")

print("J: ",Jt[-1])
print("G = ",G)
print("U = ",U)
print("V = ",v)
fim=time.time()
print("Tempo total de execução do modelo: %f" %(fim-inicio))

# Salvar a saída em csv:
dir_remoto = "/content/drive/My Drive/"
dir_local = os.getcwd() # path para rodar em máquina local ao invés do colab

pd.DataFrame(U).to_csv('drive/My Drive/data/matriz_U_q1.csv')
pd.DataFrame(v).to_csv('drive/My Drive/data/matriz_v_q1.csv')
print(U.shape)
print(v.shape)

G(t=0)= [[833, 118], [307, 1710], [513, 1281], [324, 1546], [175, 182], [1445, 71], [1244, 1826], [594, 1483], [1681, 76], [13, 1622]]

U_ij (t=0) [[0.10782003 0.07682607 0.06770869 ... 0.06438266 0.100008   0.1439595 ]
 [0.10681428 0.07780442 0.06432273 ... 0.06071012 0.10123439 0.13171643]
 [0.11313302 0.07435849 0.06379046 ... 0.06195383 0.10176691 0.12396051]
 ...
 [0.09249338 0.10070929 0.10233459 ... 0.09061256 0.09354002 0.09534656]
 [0.0894432  0.11074681 0.09129648 ... 0.08234094 0.09932442 0.09699435]
 [0.08329237 0.08902236 0.10381144 ... 0.11895211 0.08592617 0.08955567]]

J(t=0) 7634.309542201845
[[1723, 1690], [693, 1716], [754, 798], [1891, 1865], [79, 37], [1994, 1886], [1663, 1100], [594, 567], [1644, 1766], [1656, 1620]]
ERRO 934.6622790860793
t = 1 e J(t) = 6699.6472631158

[[1723, 1690], [693, 662], [754, 798], [1891, 1832], [79, 26], [1886, 1994], [1718, 1663], [567, 589], [1766, 1644], [1656, 1620]]
ERRO 24.986099082208057
t = 2 e J(t) = 6674.6611640336

[[1723, 1